# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"\x1c\n\x0c\x66ile_request\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"\x1d\n\rfile_response\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t22\n\x04\x46ile\x12*\n\tFind_file\x12\r.file_request\x1a\x0e.file_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FILE_REQUEST']._serialized_start=14
  _globals['_FILE_REQUEST']._serialized_end=42
  _globals['_FILE_RESPONSE']._serialized_start=44
  _globals['_FILE_RESPONSE']._serialized_end=73
  _globals['_FILE']._serialized_start=75
  _globals['_FILE']._serialized_end=125
# @@protoc_insertion_point(module_scope)
