# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monedas_pb2 as monedas__pb2


class MonedasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingMonedas = channel.unary_unary(
                '/Monedas/PingMonedas',
                request_serializer=monedas__pb2.EmptyMessage.SerializeToString,
                response_deserializer=monedas__pb2.PingMonedasResponse.FromString,
                )
        self.SendMoneda = channel.unary_unary(
                '/Monedas/SendMoneda',
                request_serializer=monedas__pb2.Moneda_request.SerializeToString,
                response_deserializer=monedas__pb2.Moneda_response.FromString,
                )


class MonedasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingMonedas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMoneda(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonedasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingMonedas': grpc.unary_unary_rpc_method_handler(
                    servicer.PingMonedas,
                    request_deserializer=monedas__pb2.EmptyMessage.FromString,
                    response_serializer=monedas__pb2.PingMonedasResponse.SerializeToString,
            ),
            'SendMoneda': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMoneda,
                    request_deserializer=monedas__pb2.Moneda_request.FromString,
                    response_serializer=monedas__pb2.Moneda_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Monedas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monedas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingMonedas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monedas/PingMonedas',
            monedas__pb2.EmptyMessage.SerializeToString,
            monedas__pb2.PingMonedasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMoneda(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monedas/SendMoneda',
            monedas__pb2.Moneda_request.SerializeToString,
            monedas__pb2.Moneda_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
