# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monedas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonedas.proto\"\x0e\n\x0c\x45mptyMessage\"\"\n\x13PingMonedasResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"f\n\x0eMoneda_request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\t\x12\x0c\n\x04high\x18\x03 \x01(\t\x12\x0b\n\x03low\x18\x04 \x01(\t\x12\r\n\x05\x63lose\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\"\x1f\n\x0fMoneda_response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2n\n\x07Monedas\x12\x32\n\x0bPingMonedas\x12\r.EmptyMessage\x1a\x14.PingMonedasResponse\x12/\n\nSendMoneda\x12\x0f.Moneda_request\x1a\x10.Moneda_responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monedas_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTYMESSAGE']._serialized_start=17
  _globals['_EMPTYMESSAGE']._serialized_end=31
  _globals['_PINGMONEDASRESPONSE']._serialized_start=33
  _globals['_PINGMONEDASRESPONSE']._serialized_end=67
  _globals['_MONEDA_REQUEST']._serialized_start=69
  _globals['_MONEDA_REQUEST']._serialized_end=171
  _globals['_MONEDA_RESPONSE']._serialized_start=173
  _globals['_MONEDA_RESPONSE']._serialized_end=204
  _globals['_MONEDAS']._serialized_start=206
  _globals['_MONEDAS']._serialized_end=316
# @@protoc_insertion_point(module_scope)
