# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_pb2 as file__pb2


class FileStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Find_file = channel.unary_unary(
                '/File/Find_file',
                request_serializer=file__pb2.file_request.SerializeToString,
                response_deserializer=file__pb2.file_response.FromString,
                )
        self.List_file = channel.unary_unary(
                '/File/List_file',
                request_serializer=file__pb2.file_request.SerializeToString,
                response_deserializer=file__pb2.list_response.FromString,
                )


class FileServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Find_file(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List_file(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Find_file': grpc.unary_unary_rpc_method_handler(
                    servicer.Find_file,
                    request_deserializer=file__pb2.file_request.FromString,
                    response_serializer=file__pb2.file_response.SerializeToString,
            ),
            'List_file': grpc.unary_unary_rpc_method_handler(
                    servicer.List_file,
                    request_deserializer=file__pb2.file_request.FromString,
                    response_serializer=file__pb2.list_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'File', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class File(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Find_file(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/File/Find_file',
            file__pb2.file_request.SerializeToString,
            file__pb2.file_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List_file(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/File/List_file',
            file__pb2.file_request.SerializeToString,
            file__pb2.list_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
